name: Argon2Bindings .NET Build

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15, windows-2019]
        dotnet: [ '6.0.x' ]

    if: "contains(toJSON(github.event.commits.*.message), '[ci-build]')"

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}

    - name: Restore
      run: dotnet restore *.sln

    - name: Build
      run: dotnet build --configuration Release --no-restore *.sln

    - name: Run Test Suite
      run: dotnet test --no-build --verbosity normal *.sln
